spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    jpa:
      show-sql: true
      hibernate:
        hbm2ddl:
          auto: create