server:
  port: 8080
spring:
  profiles:
    active: ${PROFILE}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      hbm2ddl:
        auto: create
